blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from views import (EntryCreate, EntryDetailView, FeedListView,
                   EntryListView, add_feed, delete_feed, add_to_read)


urlpatterns = [
    url(r'^add/$', login_required(EntryCreate.as_view()), name='entry_add'),
    url(r'entry/(?P<pk>[0-9]+)/$', EntryDetailView.as_view(), name='entry'),
    url(r'user/(?P<pk>[0-9]+)/$', EntryListView.as_view(), name='user'),
    url(r'add_feed/(?P<user_id>[0-9]+)/$', add_feed, name='add_feed'),
    url(r'delete_feed/(?P<user_id>[0-9]+)/$', delete_feed, name='delete_feed'),
    url(r'^feed/$', login_required(FeedListView.as_view()), name='user_feed'),
    url(r'^add_to_read/(?P<entry_id>[0-9]+)/$', add_to_read, name='add_to_read'),
]

testblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth

from blog import urls as blog_urls
from blog.views import EntryListView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', EntryListView.as_view(), name='home'),

    url(r'^blog/', include(blog_urls, namespace='blog')),

    # Login / logout
    url(r'^login/$', auth.login, name='login'),
    url(r'^logout/$', auth.logout, {'next_page': '/'}, name='logout'),
]

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse_lazy


class Entry(models.Model):
    name = models.CharField(verbose_name=u'Заголовок', max_length=255)
    date_create = models.DateTimeField(verbose_name=u'Дата создания',
                                       auto_now_add=True)
    description = models.TextField(verbose_name=u'Описание')
    text = models.TextField(verbose_name=u'Текст')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        app_label = 'blog'
        ordering = ['-date_create']
        verbose_name = u'Запись блога'
        verbose_name_plural = u'Записи блога'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('blog:entry', kwargs={'pk': self.id})


class UserFeed(models.Model):
    # Подписка пользователя
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name=u'Кто подписан',
                             related_name='user_feed')
    feed = models.ForeignKey(settings.AUTH_USER_MODEL,
                             verbose_name=u'На кого подписан',
                             related_name='user_readers')

    class Meta:
        app_label = 'blog'
        unique_together = (('user', 'feed'),)


class ReadEntry(models.Model):
    # Прочтенные посты
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='autor')
    entry = models.ForeignKey(Entry)

    class Meta:
        app_label = 'blog'
        unique_together = (('user', 'entry'),)

blog/views.py
# -*- coding: utf-8 -*-

# from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import IntegrityError

from models import Entry, UserFeed, ReadEntry

User = get_user_model()


class EntryListView(ListView):
    model = Entry

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            user = get_object_or_404(User, pk=self.kwargs['pk'])
            context['page_name'] = u'Блог имени ' + str(user)
            # Проверяем подписан или нет
            if self.request.user.is_authenticated() and user != self.request.user:
                context['not_autor'] = True
                context['autor'] = user
                try:
                    context['is_reader'] = bool(UserFeed.objects.get(user=self.request.user, feed=user))
                except UserFeed.DoesNotExist:
                    context['is_reader'] = False
        else:
            context['page_name'] = u'Общий блог'
        return context

    def get_queryset(self):
        if 'pk' in self.kwargs:
            return Entry.objects.filter(user=self.kwargs['pk'])
        else:
            return Entry.objects.all()


@login_required
def add_feed(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    try:
        UserFeed.objects.create(user=request.user, feed=user)
    except IntegrityError:
        pass
    return HttpResponseRedirect(reverse('blog:user', kwargs={'pk': user_id}))


@login_required
def delete_feed(request, user_id):
    UserFeed.objects.filter(user=request.user, feed=user_id).delete()
    ReadEntry.objects.filter(user=request.user, autor=user_id).delete()
    return HttpResponseRedirect(reverse('blog:user', kwargs={'pk': user_id}))


@login_required
def add_to_read(request, entry_id):
    entry = get_object_or_404(Entry, pk=entry_id)
    try:
        ReadEntry.objects.create(user=request.user, autor=entry.user, entry=entry)
    except IntegrityError:
        pass
    return HttpResponseRedirect(reverse('blog:entry', kwargs={'pk': entry_id}))


class FeedListView(ListView):
    model = Entry
    template_name = 'blog/entry_list.html'

    def get_context_data(self, **kwargs):
        context = super(FeedListView, self).get_context_data(**kwargs)
        context['page_name'] = u'Мои подписки'
        context['feed_autors'] = self.request.user.user_feed.all()
        return context

    def get_queryset(self):
        autors = self.request.user.user_feed.values('feed')
        autors = [a['feed'] for a in autors]
        return Entry.objects.filter(user__in=autors)


class EntryDetailView(DetailView):
    model = Entry
    template_name = 'blog/entry.html'

    def get_context_data(self, **kwargs):
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            autors = self.request.user.user_feed.values('feed')
            autors = [a['feed'] for a in autors]
            context['in_feed'] = context['object'].user.id in autors
            if context['in_feed']:
                try:
                    is_r = ReadEntry.objects.get(user=self.request.user,
                                                 entry=self.kwargs['pk'])
                    context['is_ready'] = bool(is_r)
                except ReadEntry.DoesNotExist:
                    context['is_ready'] = False

        return context


class EntryCreate(CreateView):
    model = Entry
    fields = ['name', 'description', 'text']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect(obj.get_absolute_url())

blog/templates/blog/entry.html
{% extends "base.html" %}

{% block content %}
    <h2>{{object}}</h2>

    {{object.text}}

    <p><i>
        Создано {{object.date_create}}
        <a href="{% url 'blog:user' pk=object.user.pk %}">
            {{object.user}}
        </a>
    </i></p>

    {% if user.is_authenticated %}
        {% if in_feed %}
            [
                {% if is_ready %}
                    Прочитано
                {% else %}    
                    <a href="{% url 'blog:add_to_read' entry_id=object.id %}">Отметить как прочитанное</a>
                {% endif %}
            ]            
        {% endif %}

    {% endif %}


{% endblock content %}

blog/templates/blog/entry_form.html
{% extends "base-form.html" %}

{% block content %}
    <h2>Создать запись</h2>
    {{block.super}}
{% endblock content %}

blog/templates/blog/entry_list.html
{% extends "base.html" %}

{% block content %}
    <h2>
        {{page_name}}

    </h2>
    
    {% if not_autor %}
        <sup>
            {% if is_reader %}
                Вы подписаны на {{page_name}}
                [<a href="{% url 'blog:delete_feed' user_id=autor.id %}">удалить из моей подписки</a>]
            {% else %}
                <a href="{% url 'blog:add_feed' user_id=autor.id %}">Подписаться</a>
            {% endif %}
        </sup>

    {% endif %}

    {% if feed_autors %}
        Вы подписаны на:

        {% for autor in feed_autors %}
            <a href="{% url 'blog:user' pk=autor.feed.pk %}">{{autor.feed}}</a>
            {% if not forloop.last %}
                ,
            {% endif %}
        {% endfor %}


    {% endif %}
    
    {% for entry in object_list %}
        <h3>
            <a href="{{entry.get_absolute_url}}">
                {{entry}}
            </a>
        </h3>
        {{entry.description}}
        
        <p><i>
            Создано {{entry.date_create}}
            <a href="{% url 'blog:user' pk=entry.user.pk %}">
                {{entry.user}}
            </a>
        </i></p>
    {% empty %}
        <p>Пока тут пусто...</p>
    {% endfor %}
{% endblock content %}

templates/base-form.html
{% extends "base.html" %}

{% block content %}
    <h2>{{page_name}}</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{form.as_table}}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="отправить">
            </td>
        </tr>
        </table>
        {{form.media}}
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Blog</title>
    <style>
        .main {
            width: 960px;
            margin: 0 auto;
            font: 13pt sans-serif;
        }
        h1 {
            border-bottom: 5px solid green;
            padding-bottom: 5px;
            color: green;
        }
        .nav {
            text-align: right;
            border-bottom: 1px solid #f1f1f1;
            padding-bottom: 15px;
            color: #c0c0c0;
            margin-bottom: 2em;
        }
        .footer {
            margin-top: 4em;
            border-top: 1px solid #f1f1f1;
            color: #c0c0c0;
            padding: 1em;
        }
    </style>
</head>
<body>
<div class="main">
    <h1>
        Test blog
    </h1>
    <div class="nav">
        <a href="/">ВсеБлог</a> |
        
        {% if user.is_authenticated %}
            <a href="{% url 'blog:entry_add' %}">Создать запись</a> |
            <a href="/blog/user/{{user.id}}/">Мой блог</a> |
            <a href="{% url 'blog:user_feed' %}">Мои подписки</a> |
            <a href="{% url 'logout' %}">Выход</a>
        {% else %}
            <a href="{% url 'login' %}">Вход</a>
        {% endif %}
    </div>
    {% block content %}{% endblock content %}


    <div class="footer">
        copyleft "{{request.META.SERVER_NAME}}" ))
    </div>
</div>
    


</body>
</html>